# Which arcs?
ALL:                True
DIRS:                [random, optimal, hypernet] # random, optimal, hypernet, edges

# For edges
LAMBDAS:            [1, 2]
# For hypernet
HYPERNET_NUMBERS:   [0]
# For optimal
OPTIMAL_NUMBERS:    [0]
# For random
COMMON_EDGES:       [0, 1]

FORCE_RETRAIN:      True # Replace retrained arcs

# Setup
LAYERS:             2
CHANNELS:           16
AUX_WEIGHT:         0.4

# Files
SAVE_FOLDER:        checkpoints
DATASET:            cifar100

# Optimization
EPOCHS:             1
BATCH_SIZE:         96
LOG_FREQUENCY:      50
UNROLLED:           False
VISUALIZATON:       False
DROP_PATH_PROB:     0.1
WORKERS:            4
GRAD_CLIP:          5.
VISUALIZATION:      False
LEARNING_RATE:      2.5e-3
WEIGHT_DECAY:       3.0e-4
