# Searching
REGIME:             random # random / optimal / hypernet / edges
# For edges and hypernet
MIN_WEIGHT:         0.3
MAX_WEIGHT:         3
TAU:                0.95
OPTIMAL_NUMBER:     0 # in {SAVE_FOLDER}/{dataset}/optimal
# For edges
LAMBDAS:            [1, 2]
# For hypernet
PIVOT_AMOUNT:       5
HYPERNET_LAMBDAS:   [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4]
P_MIN:                0

# For optimal
OPTIMAL_AMOUNT:     1
# For random
COMMON_EDGES:       [0, 1, 2, 3]



# Files
SAVE_FOLDER:        checkpoints
DATASET:            cifar100

# Architecture
N_CHOSEN:           1
LAYERS:             1
CHANNELS:           10
UNROLLED:           False

# Optimization
EPOCHS:             1
BATCH_SIZE:         64
LOG_FREQUENCY:      50
VISUALIZATION:      False
LEARNING_RATE:      2.5e-3
ARC_LEARNING_RATE:  3.0e-1

